<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3tydzx7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3tydzx7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3tydzx7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3tydzx7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3tydzx7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3tydzx7',
    'container.build_id' => '987a5b59',
    'container.build_time' => 1574065279,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3tydzx7');
